insert into TransportationTypes (Name) values ('Taxi')
insert into TransportationTypes (Name) values ('Bus')
insert into TransportationTypes (Name) values ('Drive')
insert into TransportationTypes (Name) values ('Fly')
insert into TransportationTypes (Name) values ('Walk')
insert into TransportationTypes (Name) values ('Bike')
insert into TransportationTypes (Name) values ('Boat')