insert into Users (Email,HashedPassword) values ('mikecomstock@gmail.com','$2a$10$OF9caiAHmaafsoNtvgfYi./ps5tT7k4BWlLMGoEce1lOn8lMsPTpO')

insert into TransportationTypes (Name) values ('Taxi')
insert into TransportationTypes (Name) values ('Bus')
insert into TransportationTypes (Name) values ('Drive')
insert into TransportationTypes (Name) values ('Fly')
insert into TransportationTypes (Name) values ('Walk')
insert into TransportationTypes (Name) values ('Bike')
insert into TransportationTypes (Name) values ('Boat')
insert into TransportationTypes (Name) values ('Train')